### ISSUE TITLE
mapIterator broken?

### ISSUE THREAD

**Issue by ronag** [mcollina/hwp#7]
It looks to me like map iterator will never yield unless the concurrency limit has been reached. So basically if I have a conccurency of e.g. 128, I will never get any values until very much later (if at all).

**Comment by mcollina** [comment]
That's the exepected outcome of the current code. I couldn't see an _easy_ way to implement this step-by-step and the current functionality was good enough for me - I did not need good latency.

**Comment by ronag** [comment]
I don't think the latency is the main problem here per say, it's more that you would never receive all the values unless the source if infinite.
